name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RF_ACCESS_ID: ${{ secrets.RF_ACCESS_ID }}
      RF_SECRET_ACCESS_KEY: ${{ secrets.RF_SECRET_ACCESS_KEY }}
      RF_ROOT_URL: ${{ secrets.RF_ROOT_URL }}
      DOCKER_CONFIG: ${{ github.workspace }}/.docker

    steps:
      - uses: actions/checkout@v4

      # --- RapidFort credential helper setup ---
      - name: Prepare Docker config dir
        run: mkdir -p "$DOCKER_CONFIG"

      - name: Download RapidFort docker credential helper
        run: |
          set -euo pipefail
          url="${RF_ROOT_URL}/cli/docker-credential-rfcurated-$(uname)-$(uname -m).tar.gz"
          echo "Downloading credential helper from: $url"
          curl -fsSL -o docker-credential-rfcurated.tar.gz "$url"

      - name: Install credential helper
        run: |
          sudo tar -xzf docker-credential-rfcurated.tar.gz -C /usr/local/bin
          sudo chmod +x /usr/local/bin/docker-credential-rfcurated
          echo quay.io | /usr/local/bin/docker-credential-rfcurated init
          echo "Docker config after init:"
          cat "$DOCKER_CONFIG/config.json"

      # --- Optional: Pull image(s) from Quay or RapidFort ---
      - name: Pull example image
        run: |
          docker pull quay.io/rfcurated/alpine:3.21-rfcurated
          docker images
